export { api, initApiClient } from "./client"
export type { ApiResult, ApiError, TokenProvider, ApiClientConfig } from "./client"

export { authApi } from "./auth"
export { fragmentApi } from "./fragments"
export { taskApi } from "./tasks"
export { eventApi } from "./events"
export { projectApi } from "./projects"
export { knowledgeApi } from "./knowledge"
export { dashboardApi } from "./dashboard"
export { userApi } from "./users"
export { notificationApi } from "./notifications"
